name: Update dest.txt

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  replicate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run dir
        run: dir

      - name: Show src contents
        run: cat src.txt

      - name: Update files
        run: cp src.txt dest.txt
        
      - name: Show dest contents
        run: cat dest.txt
        
      - name: Push changes
        run: |
          git config --global user.name "Kapil Gupta"
          git config --global user.email "kgupta219000@gmail.com"
          git add .
          git commit -m "Updating dest.txt"
          git push
