name: Update README.md

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  replicate:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ./project1
      
      - uses: actions/checkout@v3
        with:
          repository: kguptaDemoOrg/.github
          token: ${{ secrets.GH_TOKEN }}
          path: ./.github

      - name: Replicate file
        run: cp ./project1/README.md ./.github/profile/README.md
        
      - name: Push changes to GitHub
        run: |
          cd ./.github
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated README.md"
          git push
